#!/usr/bin/env python
# -*- coding: UTF-8 -*-
# File: configuration.py
"""A place to store the configuration."""


STATE_CACHING_SECONDS = 30
REQUEST_TIMEOUT = 9

STATES = {0: 'Comfort',
          1: 'Home',
          2: 'Sleep',
          3: 'Away',
          4: 'Unknown',
          5: 'Unknown'}
#
#
# DEFAULT_STATE = {'deviceConfigInfo': {'device': []},
#                  'deviceStatusInfo': {'device': [],
#                                       'inSwitchAllTotal': {'avgUsage': 0.0,
#                                                            'currentState': 0,
#                                                            'currentUsage': 0.0,
#                                                            'dayUsage': 0.0}},
#                  'gasUsage': {'avgDayValue': 0.0,
#                               'avgValue': 0.0,
#                               'dayCost': 0.0,
#                               'dayUsage': 0,
#                               'isSmart': 0,
#                               'meterReading': 0,
#                               'value': 0},
#                  'powerUsage': {'avgDayValue': 0.0,
#                                 'avgProduValue': 0,
#                                 'avgValue': 0.0,
#                                 'dayCost': 0.0,
#                                 'dayCostProduced': 0.0,
#                                 'dayLowUsage': 0,
#                                 'dayUsage': 0,
#                                 'isSmart': 0,
#                                 'maxSolar': 0,
#                                 'meterReading': 0,
#                                 'meterReadingLow': 0,
#                                 'meterReadingLowProdu': 0,
#                                 'meterReadingProdu': 0,
#                                 'value': 0,
#                                 'valueProduced': 0,
#                                 'valueSolar': 0},
#                  'smokeDetectors': {'device': []},
#                  'thermostatInfo': {'activeState': 0,
#                                     'boilerModuleConnected': 0,
#                                     'burnerInfo': '0',
#                                     'currentDisplayTemp': 0,
#                                     'currentModulationLevel': 0,
#                                     'currentSetpoint': 0,
#                                     'errorFound': 0,
#                                     'haveOTBoiler': 0,
#                                     'nextProgram': 0,
#                                     'nextSetpoint': 0,
#                                     'nextState': 0,
#                                     'nextTime': 0,
#                                     'otCommError': '0',
#                                     'programState': 0,
#                                     'realSetpoint': 0},
#                  'thermostatStates': {'state': [{'dhw': 1,
#                                                  'id': 0,
#                                                  'tempValue': 0},
#                                                 {'dhw': 1,
#                                                  'id': 1,
#                                                  'tempValue': 0},
#                                                 {'dhw': 1,
#                                                  'id': 2,
#                                                  'tempValue': 0},
#                                                 {'dhw': 1,
#                                                  'id': 3,
#                                                  'tempValue': 0},
#                                                 {'dhw': 1,
#                                                  'id': 4,
#                                                  'tempValue': 0}]}}
